services:
  app:
    image: todo-front-dev
    build:
      context: ./
      dockerfile: dev.Dockerfile # Your Dockerfile for the frontend
    volumes:
      - ./:/usr/src/app
    ports:
      - 5173:5173
    container_name: todo-front-dev
  # debug-helper:
  #   image: busybox
