FROM node:20 AS test-stage
WORKDIR /usr/src/app

COPY . .
RUN npm ci 
RUN CI=true npm test

FROM test-stage AS build-stage
WORKDIR /usr/src/app
COPY . .
RUN npm ci --only=production
ENV VITE_BACKEND_URL="http://127.0.0.1:3000/"
RUN npm run build

# Use Nginx to serve the static files
FROM nginx:1.25-alpine
COPY --from=build-stage /usr/src/app/dist /usr/share/nginx/html
