services:
  # frontend
  app:
    image: todo-frontend-dev
    container_name: todo-frontend-dev
    build:
      context: .
      dockerfile: ./todo-frontend/dev.Dockerfile
    # ports:
    #   - 5173:3000
    volumes:
      - ./todo-frontend:/usr/src/app
    environment:
      - VITE_BACKEND_URL=http://localhost:8080/api

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo_data:/data/db

  redis:
    image: redis
    container_name: redis
    ports:
      - '6379:6379'
    environment:
      REDIS_PASSWORD: redis_example
    command:
      [
        'redis-server',
        '--appendonly',
        'yes',
        '--appendfilename',
        'appendonly.aof',
        '--dir',
        '/data/redis'
      ]
    volumes:
      - redis_data:/data/redis

  server:
    image: todo-backend-dev
    container_name: todo-backend-dev
    build:
      context: .
      dockerfile: ./todo-backend/dev.Dockerfile
    # ports:
    #   - 3000:3000
    volumes:
      - ./todo-backend:/usr/src/app
    environment:
      REDIS_URL: redis://redis:6379
      MONGO_URL: mongodb://the_username:the_password@mongo:27017/the_database
    depends_on:
      - mongo
      - redis

  #  reverse proxy
  nginx:
    image: nginx:1.20.1
    container_name: nginx_rev_p
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    depends_on:
      - app
      - server

volumes:
  mongo_data:
  redis_data:
